### ISSUE TITLE
Empty Google Sheet

### ISSUE THREAD

**Issue by yingsun-ucsd** [IGVF-DACC/igvf-metadata-submitter#37]
I noticed that the Google Sheet I downloaded is empty. Could you please confirm if this is intentional or if there might be an issue? Thanks.

<img width="1153" alt="Screenshot 2024-08-28 at 4 41 12 PM" src="https://github.com/user-attachments/assets/66efff05-bcfd-4d00-8f3d-8c6a4dcbf47f">

**Comment by meenakshikagda** [comment]
Hi Ying,
I think you need to make a copy and work within google-sheets. I don't see any issue with this. The first tab Readme is populated. Please follow the instructions here to set it up: https://data.igvf.org/help/data-submission/submission-by-appscript-documentation/

**Comment by yingsun-ucsd** [comment]
@meenakshikagda Thank you for your response. Aside from the first tab, "Readme," all the other tabs in my file are currently empty. Should I expect additional tabs like "human-donor," "biosample," "replicate," etc.?

Thank you!

**Comment by meenakshikagda** [comment]
Well, you will need to populate the tabs on your own. We don't make a custom tab because different users will have different needs. So the instructions to do that are listed here: https://data.igvf.org/help/data-submission/submission-by-appscript-documentation/ Also, which lab are you from? We could chat over slack since that would be quicker for us to respond.
